allow_debugging: off
template_function:  _.template
template_namespace: Denwen.JST

javascripts:
  application:
    - public/javascripts/libs/jquery-1.7.1.js
    - public/javascripts/libs/jquery-timeago.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
    - public/javascripts/libs/bootstrap.js
    - public/javascripts/libs/swfupload.js
    - public/javascripts/extensions.js
    - public/javascripts/config.js
    - public/javascripts/application.js
    - public/javascripts/enumerations.js
    - public/javascripts/analytics.js
    - public/javascripts/message_drawer.js
    - public/javascripts/helpers.js
    - public/javascripts/global.js
    - public/javascripts/window_listener.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js
    - public/javascripts/partials/**/*.js
    - public/javascripts/views/**/*.js
    - app/views/comments/*.jst
    - app/views/actions/*.jst
    - app/views/products/*.jst
    - app/views/users/*.jst
    - app/views/stores/*.jst
    - app/views/followings/*.jst
    - app/views/contacts/*.jst
    - app/views/collections/*.jst
    - app/views/suggestions/*.jst
  home:
    - public/javascripts/libs/jquery-1.7.1.js
stylesheets:
  application:
    - public/stylesheets/application.css
    - public/stylesheets/bootstrap.css
    - public/stylesheets/velcro.css
  home:
    - public/stylesheets/bootstrap.css
    - public/stylesheets/velcro.css
    - public/stylesheets/home.css
