--- 
javascripts: 
- application: 
  - jquery-1.4.3
  - jquery-easing
  - jquery-cycle-lite
  - underscore
  - backbone
  - extensions
  - window_listener
  - user
  - comment
  - search
  - product_image
  - scroll_view_controller
  - application
  - product
  - new_product_view_controller
stylesheets: 
- application: 
  - application
