--- 
javascripts: 
- home: 
  - libs/jquery-1.4.3
- application: 
  - libs/jquery-1.4.3
  - libs/jquery-easing
  - libs/jquery-cycle-lite
  - libs/jquery-autocomplete
  - libs/underscore
  - libs/backbone
  - extensions
  - application
  - analytics
  - global
  - window_listener
  - models/user
  - models/comment
  - models/search
  - models/product_image
  - models/product
  - collections/product_images
  - views/user_byline_view
  - views/comment_input_view
  - views/product_input_view
  - views/product_image_view
  - views/product_images_view
  - views/facebook_view
  - views/facebook_invite_view
stylesheets: 
- application: 
  - application
- home: 
  - home
