allow_debugging: off
template_function:  _.template
template_namespace: Denwen.JST

javascripts:
  application:
    - public/javascripts/libs/jquery-1.4.3.js
    - public/javascripts/libs/jquery-timeago.js
    - public/javascripts/libs/jquery-autocomplete.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
    - public/javascripts/extensions.js
    - public/javascripts/application.js
    - public/javascripts/analytics.js
    - public/javascripts/global.js
    - public/javascripts/window_listener.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js
    - public/javascripts/partials/*.js
    - public/javascripts/views/*.js
    - app/views/comments/comment.jst
    - app/views/products/product.jst
stylesheets:
  application:
    - public/stylesheets/application.css
  home:
    - public/stylesheets/home.css
