allow_debugging: off
template_function:  _.template
template_namespace: Denwen.JST

javascripts:
  application:
    - public/javascripts/libs/jquery-1.7.1.js
    - public/javascripts/libs/jquery-timeago.js
    - public/javascripts/libs/underscore.js
    - public/javascripts/libs/backbone.js
    - public/javascripts/libs/bootstrap.js
    - public/javascripts/libs/swfupload.js
    - public/javascripts/support/extensions.js
    - public/javascripts/config.js
    - public/javascripts/application.js
    - public/javascripts/enumerations.js
    - public/javascripts/support/analytics.js
    - public/javascripts/support/message_drawer.js
    - public/javascripts/support/helpers.js
    - public/javascripts/support/notification_manager.js
    - public/javascripts/support/global.js
    - public/javascripts/support/infinite_scroller.js
    - public/javascripts/models/*.js
    - public/javascripts/collections/*.js
    - public/javascripts/partials/**/*.js
    - public/javascripts/views/**/*.js
    - app/views/comments/*.jst
    - app/views/likes/*.jst
    - app/views/products/*.jst
    - app/views/purchases/**/*.jst
    - app/views/contacts/*.jst
    - app/views/suggestions/*.jst
    - app/views/followings/*.jst
    - app/views/users/*.jst
    - app/views/notifications/*.jst
    - app/views/welcome/create/*.jst
  home:
    - public/javascripts/libs/jquery-1.7.1.js
    - public/javascripts/libs/bootstrap-home.js
stylesheets:
  application:
    - public/stylesheets/bootstrap.css
    - public/stylesheets/general.css
    - public/stylesheets/main.css
    - public/stylesheets/mobile.css
  home:
    - public/stylesheets/bootstrap.css
    - public/stylesheets/general.css
    - public/stylesheets/home.css
  admin:
    - public/stylesheets/bootstrap.css
