--- 
javascripts: 
- application: 
  - jquery-1.4.3.min
  - swfupload
  - application_controller
  - scroll_view_controller
  - product
  - new_product_view_controller
stylesheets: 
- application: 
  - application
