:consumer_key: ZYFy5zrte9fKABpNqRE3IQ
:consumer_secret: oxYih93ZJRMhyD538iyCMRrxU4MUAsXK7cmDNEwdIww
:accounts: [
  {
  :token: 19427356-CRclpAaQmiyFw4ODzfVwNeQ50xBx8loG8ttfYQ3Xo,
  :secret: meT0qzzOEjPehTgEfALJ72ahSFux7qMkSy98JeH0U,
  :handle: nataliesatmine,
  :enabled: false,
  :templates: [
    {
    :tweet: "@name I just built a site for tweeting pics of what you bought called 'Mine', here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name cool! I just built 'Mine' a site for tweeting pics of what you bought, here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Hey @name, I built a site called 'Mine' for tweeting purchases, see if you like it! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "saw ur tweet @name - I built this for tweeting stuff you've bought: http://getmine.com/try You'll love it!",
    :media: nil},
    {
    :tweet: "@name really cool! On Mine (http://getmine.com/try) you can tweet pics of what you bought. You'll love it!",
    :media: nil}]
  },
  {
  :token: 47768007-lc0ICcWUnkQJS5Pb2pfYA1qIs6gqIS7Uqh3sEindt,
  :secret: fIr97UY1cLwb3dz8aVCDJLk30fYGIdrujHs661GI,
  :handle: rebeccasuperpet,
  :enabled: false,
  :templates: [
    {
    :tweet: "Thats cool @name! I'm working on Mine, a site for tweeting purchases - check it out! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Pretty cool @name! I think you'll like this site I'm working on for tweeting purchases: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "That is so neat - @name have you tried using Mine (http://getmine.com/try) for tweeting what you bought?",
    :media: nil},
    {
    :tweet: "Love it! @name have you tried using Mine (http://getmine.com/try) for tweeting what you bought? Try it!",
    :media: nil},
    {
    :tweet: "Want! Where can I buy that? @name You should start a Mine account for stuff you buy! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name Did you get it on sale? Btw you might like http://getmine.com/try for tweeting stuff you've bought!",
    :media: nil},
    {
    :tweet: "Wow that's neat. @name you should try posting on http://getmine.com/try for tweeting what you just bought!",
    :media: nil}]
  },
  {
  :token: 45032868-lshRI4HtdHwFZYu4fubj2CDsodEFRCWssHNeS8K5G, 
  :secret: OvAdFrTryJDrVfkcbmKh7UNT441d0ZTGWx25vk52M, 
  :tw_user_id: 45032868,
  :handle: sarahatmine,
  :enabled: true,
  :templates: [
    {
    :tweet: "@name that's cool - if you go to http://getmine.com/try you can tweet pics of what you bought. Try it :)",
    :media: nil},
    {
    :tweet: "@name that is cool! On Mine you can tweet pics of what you bought http://getmine.com/try See if you like it!",
    :media: nil},
    {
    :tweet: "@name Awesome! Try Mine to tweet pics of what you bought http://getmine.com/try You'd love it!",
    :media: nil},
    {
    :tweet: "@name That is great! Have you tried Mine for tweeting pics of what you bought http://getmine.com/try Try it!",
    :media: nil},
    {
    :tweet: "@name That's cool! Definitely try Mine http://getmine.com/try for tweeting what you bought. You'd love it!",
    :media: nil}]
  },
  {
  :token: 349191075-MdFJ3aP9ImNFgYQUWXMsUXYBaUorOsIpQrTSwRQ0, 
  :secret: bXAoGN3sLIrtO4P1LGwwsvLi0uVZs0JK9eTmSFPlLe0, 
  :handle: JRoth1979, 
  :enabled: true,
  :templates: [
    {
    :tweet: "I sometimes tweet what I buy too, @name. Have you tried Mine http://getmine.com/try? - I love it!",
    :media: nil},
    {
    :tweet: "Hey @name while you're tweeting stuff you bought, check out Mine, here http://getmine.com/try!",
    :media: nil},
    {
    :tweet: "Hey @name have you tried Mine for tweeting your purchases? http://getmine.com/try really nicely designed.",
    :media: nil},
    {
    :tweet: "nice! On Mine (http://getmine.com/try) you can tweet pics of what you bought. I think you'd like it, @name!",
    :media: nil},
    {
    :tweet: "cool :) On Mine http://getmine.com/try you can tweet pics of what you bought to twitter or just close friends. Try it!",
    :media: nil},
    {
    :tweet: "Hey @name, where did you get that? You can tell others about your recent purchases at http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Want! Where can I buy that? @name You should start a Mine account for stuff you buy! http://getmine.com/try",
    :media: nil}]
  },
  {
  :token: 203171199-AiE830bCS64ncAYXbGd3EacfOkXEU4Ewsncfwt0e, 
  :secret: sfz3YZ6ym61OhqLNSHnkw4DhdrfN5uzkU1GmiEDJJs4, 
  :handle: gabbysmine,
  :enabled: false,
  :templates: [
    {
    :tweet: "Hey @name that looks really cool - you should show it off on your Mine page! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Hey @name, where did you get that? You can tell others about your recent purchases at http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Want! Where can I buy that? @name You should start a Mine account for stuff you buy! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name Did you get it on sale? Btw you might like http://getmine.com/try for tweeting stuff you've bought!",
    :media: nil},
    {
    :tweet: "I want that too! @name had you heard of http://getmine.com/try for tweeting about stuff you've bought?",
    :media: nil},
    {
    :tweet: "@name you should show that off on a Mine page! I think you might like it: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name where can I buy that? Please add it on Mine, here: http://getmine.com/try!",
    :media: nil},
    {
    :tweet: "OMG @name I love it! Please please start a Mine page for all the cool stuff you have! http://getmine.com/try",
    :media: nil}]
  },
  {
  :token: 28276812-JWecBVP3nnRVvmPCJKfUo7wyIcbaADVqGkKANu02x, 
  :secret: 5Fhm5xNVAntSA9KzjgRP0wtkcWt5vh0bwZjVFkoWKVg, 
  :handle: JulietsMine,
  :enabled: false,
  :templates: [
    {
    :tweet: "@name That's cool! You should try Mine http://getmine.com/try for tweeting what you bought. You'd love it!",
    :media: nil},
    {
    :tweet: "@name cool! Tried Mine http://getmine.com/try for tweeting pics of what you bought? You'd love it!",
    :media: nil},
    {
    :tweet: "@name that's awesome! I'm working on http://getmine.com/try for sharing cool stuff you buy. Def try it!",
    :media: nil},
    {
    :tweet: "pretty neat @name! I built a site for sharing stuff you buy http://getmine.com/try You'll love it!",
    :media: nil},
    {
    :tweet: "Saw ur tweet @name - I built this for tweeting stuff you've bought: http://getmine.com/try You'll love it!",
    :media: nil}]
  },
  {
  :token: 128315504-DtZvx6vmlDxHsyy9yQswG3gS2Lyez70QRMFBhbbs,
  :secret: IJdpua5PSADtHaZFuDyRHhdpxdikI9Lkm08Hp4, 
  :handle: jennyfstanton,
  :enabled: false,
  :templates: [
    {
    :tweet: "Thats cool @name! I'm working on Mine, a site for tweeting purchases - check it out! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Pretty cool @name! I think you'll like this site I'm working on for tweeting purchases: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "That is so neat - @name have you tried using Mine (http://getmine.com/try) for tweeting what you bought?",
    :media: nil},
    {
    :tweet: "Love it! @name have you tried using Mine (http://getmine.com/try) for tweeting what you bought? Try it!",
    :media: nil},
    {
    :tweet: "Wow that's neat. @name you should try posting on http://getmine.com/try for tweeting what you just bought!",
    :media: nil}]
  },
  {
  :token: 78746587-RskUsbw4oRvH4HbEPHYLbWvpeIxOW1EYlTNPfadSM, 
  :secret: MY7TGBmCBD6FlIghGNUA6TEiEpYX9wjLLZ2YShkqz7s, 
  :handle: philips_samf, 
  :enabled: false,
  :templates: [
    {
    :tweet: "@name that's cool! On Mine (http://getmine.com/try) you can tweet pics of what you bought. Check it out!",
    :media: nil},
    {
    :tweet: "nice! On Mine (http://getmine.com/try) you can tweet pics of what you bought. I think you'd like it, @name!",
    :media: nil},
    {
    :tweet: "Hey @name saw your tweet. You can post stuff you buy better on Mine http://getmine.com/try You'll like it :)",
    :media: nil},
    {
    :tweet: "You should try Mine, @name, a new website for telling friends when you buy something: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "pretty cool! Have you tried Mine, @name? a site for telling friends what you bought http://getmine.com/try",
    :media: nil}]
  },
  {
  :token: 155011786-Myt8HR1yHVWFIHAdxjtoWA5cJEOsEDn8daLlRNln, 
  :secret: JzlcI152JdhHHI1ucOhTXnyuSHgTncuWYhOqxTrhz0, 
  :handle: MikeFentonSF, 
  :enabled: false,
  :templates: [
    {
    :tweet: "Hey I saw your last tweet. Why not post on Mine http://getmine.com/try? It's made for tweeting what you buy - Try it!",
    :media: nil},
    {
    :tweet: "Hey @name you should start a Mine profile - add that and other stuff you bought, here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "nice! On Mine (http://getmine.com/try) you can tweet pics of what you bought. I think you'd like it, @name!",
    :media: nil},
    {
    :tweet: "Hey @name while you're tweeting stuff you bought check out Mine here http://getmine.com/try It's made for it",
    :media: nil},
    {
    :tweet: "I sometimes tweet what I buy too, @name. Have you tried Mine http://getmine.com/try? - you'd love it!",
    :media: nil}]
  },
  {
  :token: 20282200-Z4KJgW13VK6D0hxOR4n0yvl42WAEnm0kbXqbBOTin, 
  :secret: 6c5pbMfjSkta8gmoOdkF5HKx0GanKegbnAwOsIqEIT4,
  :handle: mstantonSF,
  :enabled: false,
  :templates: [
    {
    :tweet: "I sometimes tweet what I buy too, @name. Have you tried Mine http://getmine.com/try? - I love it!",
    :media: nil},
    {
    :tweet: "Hey @name while you're tweeting stuff you bought, check out Mine, here http://getmine.com/try!",
    :media: nil},
    {
    :tweet: "Hey @name have you tried Mine for tweeting your purchases? http://getmine.com/try really nicely designed.",
    :media: nil},
    {
    :tweet: "nice! On Mine (http://getmine.com/try) you can tweet pics of what you bought. I think you'd like it, @name!",
    :media: nil},
    {
    :tweet: "cool :) On Mine http://getmine.com/try you can tweet pics of what you bought to twitter or just close friends. Try it!",
    :media: nil}]
  }
]
