:consumer_key: 5M8DIWAdEJRKlTW5d9vw
:consumer_secret: JSSRkH53nsTbvppypEmsmWJHini1CE0PJuwWV8ck4sc 
:accounts: [
  {
  :token: 20894612-Wb7ffoyvFSXnlyAJt44bCVuOFwegcoVDqsSiX6K04,
  :secret: cqbjSW2hVVx6bH7PRl5TJYyIiy0lxTQOuLe4W20gnU,
  :templates: [
    {
    :tweet: "saw ur tweet @name- I built this for tweeting stuff you've bought: http://getmine.com/try Could you try it?",
    :media: nil},
    {
    :tweet: "@name I just built a site called 'Mine' for tweeting about purchases. Please try it! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name I just built a site for tweeting pics of what you bought called 'Mine', here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Hey @name, I built a site called 'Mine' for tweeting purchases, see if you like it! http://getmine.com/try", 
    :media: nil},
    {
    :tweet: "Awesome! I'm actually working on a site for sharing cool stuff you buy. You can try it here: http://getmine.com/try",
    :media: nil}]
  },
  {
  :token: 158595960-hIOCkVpoyRAbQl6y2QgdDjYnkpGwEPOnWczk5HPA,
  :secret: B9cTjc6HZ0Pso03d1LVzEhDBYOYqNzMxoernFcY9zg,
  :templates: [
    {
    :tweet: "Hey @name saw ur tweet. I'm building a site for tweeting purchases. Mind trying it? http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Awesome! @name here's my site for tweeting pics of things you buy. Try it? Thank you! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Nice! Would you mind trying this service for tweeting purchases I'm building? Let me know thx! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Cool! @name have you tried Mine, a site for tweeting ur purchases? Let me know thx! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name I built http://getmine.com/try for tweeting purchases. Like to try it?",
    :media: nil}]
  },
  {
  :token: 45032868-u6AmUUC3Lwb64TVQifzkEgey9r6zayISQXy0aJ2SF, 
  :secret: 4TJIHLVPDrA29dohWvdn6lxcferKWPFCEelZpHIVo,
  :tw_user_id: 45032868,
  :templates: [
    {
    :tweet: "Hey @name I'm actually working on a site for tweeting purchases. Try it? thx! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name that's cool - if you go to http://getmine.com/try you can tweet pics of what you bought. Try it :)",
    :media: nil},
    {
    :tweet: "Awesome! I'm working on a simple site for sharing cool stuff you buy. You can try it here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name have you tried http://getmine.com/try for tweeting purchases? It's easy to use and looks great. Try it!",
    :media: nil},
    {
    :tweet: "Hey @name I'm testing http://getmine.com/try with people sharing purchases on here. Love you to try it! thx!",
    :media: nil}]
  },
  {
  :token: 222575900-PhzdRuJVuyIJP9W4TmHZrDXDtuBYaMojaPT1LDki,
  :secret: uP90oTC9hThJ5ZsdKQ164o23RaruneXvNHOfmxGfjM,
  :templates: [
    {
    :tweet: "Hey @name! I've created a site especially for tweeting purchases. See if you like it: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name that's cool! On Mine (http://getmine.com/try) you can tweet pics of what you bought. You'll love it!",
    :media: nil},
    {
    :tweet: "Awesome! I'm working on a simple site for sharing cool stuff you buy. I think you'd love it! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name have you tried Mine (http://getmine.com/try) for tweeting purchases? It looks great, you'd love it!",
    :media: nil},
    {
    :tweet: "Hey @name! I'm testing http://getmine.com/try with people sharing purchases on here. I Think you'd love it",
    :media: nil}]
  },
  {
  :token: 203171199-jobUkvNVdlmZStS3BxUQHbRGDggs76cml7A8tiAQ, 
  :secret: bo9dvzPtKU7QB2Aa8VCbgCl9ij3GQTgqRk5N74Fjo, 
  :templates: [
    {
    :tweet: "Hey @name that looks really cool - you should show it off on your Mine page! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Hey @name, where did you get that? You can tell others about your recent purchases at http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Want! Where can I buy that? @name You should start a Mine account for stuff you buy! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name Did you get it on sale? Btw you might like http://getmine.com/try for tweeting stuff you've bought!",
    :media: nil},
    {
    :tweet: "I want that too! @name had you heard of http://getmine.com/try for tweeting about stuff you've bought?",
    :media: nil},
    {
    :tweet: "@name you should show that off on a Mine page! I think you might like it: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name where can I buy that? Please add it on Mine, here: http://getmine.com/try!",
    :media: nil},
    {
    :tweet: "OMG @name I love it! Please please start a Mine page for all the cool stuff you have! http://getmine.com/try",
    :media: nil}]
  }
]
