:consumer_key: 5M8DIWAdEJRKlTW5d9vw
:consumer_secret: JSSRkH53nsTbvppypEmsmWJHini1CE0PJuwWV8ck4sc 
:accounts: [
  {
  :token: 20894612-Wb7ffoyvFSXnlyAJt44bCVuOFwegcoVDqsSiX6K04,
  :secret: cqbjSW2hVVx6bH7PRl5TJYyIiy0lxTQOuLe4W20gnU,
  :templates: [
    {
    :tweet: "saw ur tweet @name- I built this for tweeting stuff you've bought: http://getmine.com/try Could you try it?",
    :media: nil},
    {
    :tweet: "@name I just built a site called 'Mine' for tweeting about purchases. Please try it! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name I just built a site for tweeting pics of what you bought called 'Mine', here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Hey @name, I built a site called 'Mine' for tweeting purchases, see if you like it! http://getmine.com/try", 
    :media: nil},
    {
    :tweet: "Awesome! I'm actually working on a site for sharing cool stuff you buy. You can try it here: http://getmine.com/try",
    :media: nil}]
  },
  {
  :token: 158595960-hIOCkVpoyRAbQl6y2QgdDjYnkpGwEPOnWczk5HPA,
  :secret: B9cTjc6HZ0Pso03d1LVzEhDBYOYqNzMxoernFcY9zg,
  :templates: [
    {
    :tweet: "Hey @name saw ur tweet. I'm building a site for tweeting purchases. Mind trying it? http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Awesome! @name here's my site for tweeting pics of things you buy. Try it? Thank you! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Nice! Would you mind trying this service for tweeting purchases I'm building? Let me know thx! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "Cool! @name have you tried Mine, a site for tweeting ur purchases? Let me know thx! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name I built http://getmine.com/try for tweeting purchases. Like to try it?",
    :media: nil}]
  },
  {
  :token: 621545739-sU4RsKRE0dZRdmzk18x4TLGopYCVy4Nxjnytdatl, 
  :secret: FOLqfagnpZo7ifjtMrzfSR0z198p3sa0Gcdo3sqvcSc,
  :tw_user_id: 621545739,
  :templates: [
    {
    :tweet: "Hey @name I'm actually working on a site for tweeting purchases. Try it? thx! http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name that's cool - if you go to http://getmine.com/try you can tweet pics of what you bought. Try it :)",
    :media: nil},
    {
    :tweet: "Awesome! I'm working on a simple site for sharing cool stuff you buy. You can try it here: http://getmine.com/try",
    :media: nil},
    {
    :tweet: "@name have you tried http://getmine.com/try for tweeting purchases? It's easy to use and looks great. Try it!",
    :media: nil},
    {
    :tweet: "Hey @name I'm testing http://getmine.com/try with people sharing purchases on here. Love you to try it! thx!",
    :media: nil}]
  }
]
